### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by noamhoze** [noamhoze/walabot#54]
Here are the remaining issues order by level of importance:

- [ ] Write the Wiki section #20 
- [ ] Finish the German page #50
- [ ] Rich search results #38
- [ ] Scrolling event #46 
- [ ] Configuration files#51 
- [ ] New test pages for DIY and Pro #53
- [ ] Fix the bug mentioned in the last comment in #47 
- [ ] Support old browsers #45 
- [ ] Modify the option to subscribe #14

**Comment by noamhoze** [comment]
@amitzur, please work today on #58, #56.
